---
baseurl: "http://www.yangcs.net/"
DefaultContentLanguage: "zh-cn"
hasCJKLanguage: true
languageCode: "zh-cn"
title: "Ryan Yang" 
theme: "beautifulhugo"
metaDataFormat: "yaml"
subtitle: "I can help you building Cloud Native confidence"
dateFormat: "January 2, 2006"
description: "Cloud Native🤘 Big Data"
algolia:
  index: "blog"
  key: "62fd06bd949abb4211bfab0aa288f67b"
  appID: "4BELQK2TOI"
---
