version: '2'
services:

  oneindex:
    image: yinaoxiong/oneindex
    restart: always
    volumes:
      - /data/oneindex:/var/www/html
    networks:
      - default
    expose:
      - "80"

  oneindex-envoy:
    image: envoyproxy/envoy-alpine:latest
    restart: always
    volumes:
      - ./oneindex-envoy.yaml:/etc/envoy/envoy.yaml
    network_mode: "service:oneindex"

networks:
  default:
    external:
      name: yang
